"""Initial migration

Revision ID: 0b046241147d
Revises: 
Create Date: 2026-08-22 20:54:05.008322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b046241147d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seat_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_categories_created_at'), 'seat_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_seat_categories_id'), 'seat_categories', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'ORGANISER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_created_at'), 'venues', ['created_at'], unique=False)
    op.create_index(op.f('ix_venues_id'), 'venues', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('organiser_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organiser_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_organiser_id'), 'events', ['organiser_id'], unique=False)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_index(op.f('ix_events_venue_id'), 'events', ['venue_id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('row_identifier', sa.String(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('x_pos', sa.Integer(), nullable=True),
    sa.Column('y_pos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['seat_categories.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seats_created_at'), 'seats', ['created_at'], unique=False)
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_reference'), 'bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_bookings_created_at'), 'bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookings_event_id'), 'bookings', ['event_id'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('event_category_pricings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['seat_categories.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_category_pricings_created_at'), 'event_category_pricings', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_category_pricings_id'), 'event_category_pricings', ['id'], unique=False)
    op.create_table('show_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('physical_seat_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'HELD', 'BOOKED', name='seatstatus'), nullable=False),
    sa.Column('held_by_id', sa.Integer(), nullable=True),
    sa.Column('hold_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['held_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['physical_seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'physical_seat_id', name='uq_show_seat_event_physical')
    )
    op.create_index(op.f('ix_show_seats_created_at'), 'show_seats', ['created_at'], unique=False)
    op.create_index(op.f('ix_show_seats_event_id'), 'show_seats', ['event_id'], unique=False)
    op.create_index(op.f('ix_show_seats_held_by_id'), 'show_seats', ['held_by_id'], unique=False)
    op.create_index(op.f('ix_show_seats_hold_expires_at'), 'show_seats', ['hold_expires_at'], unique=False)
    op.create_index(op.f('ix_show_seats_id'), 'show_seats', ['id'], unique=False)
    op.create_index(op.f('ix_show_seats_physical_seat_id'), 'show_seats', ['physical_seat_id'], unique=False)
    op.create_index(op.f('ix_show_seats_status'), 'show_seats', ['status'], unique=False)
    op.create_table('waitlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OFFERED', 'ACCEPTED', 'CANCELLED', 'EXPIRED', name='waitliststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['seat_categories.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_entries_category_id'), 'waitlist_entries', ['category_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_created_at'), 'waitlist_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_event_id'), 'waitlist_entries', ['event_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_id'), 'waitlist_entries', ['id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_status'), 'waitlist_entries', ['status'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_user_id'), 'waitlist_entries', ['user_id'], unique=False)
    op.create_table('booking_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('show_seat_id', sa.Integer(), nullable=False),
    sa.Column('price_at_booking', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['show_seat_id'], ['show_seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_seats_created_at'), 'booking_seats', ['created_at'], unique=False)
    op.create_index(op.f('ix_booking_seats_id'), 'booking_seats', ['id'], unique=False)
    op.create_table('waitlist_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waitlist_entry_id', sa.Integer(), nullable=False),
    sa.Column('show_seat_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACCEPTED', 'EXPIRED', 'DECLINED', name='offerstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['show_seat_id'], ['show_seats.id'], ),
    sa.ForeignKeyConstraint(['waitlist_entry_id'], ['waitlist_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_offers_created_at'), 'waitlist_offers', ['created_at'], unique=False)
    op.create_index(op.f('ix_waitlist_offers_expires_at'), 'waitlist_offers', ['expires_at'], unique=False)
    op.create_index(op.f('ix_waitlist_offers_id'), 'waitlist_offers', ['id'], unique=False)
    op.create_index(op.f('ix_waitlist_offers_show_seat_id'), 'waitlist_offers', ['show_seat_id'], unique=False)
    op.create_index(op.f('ix_waitlist_offers_status'), 'waitlist_offers', ['status'], unique=False)
    op.create_index(op.f('ix_waitlist_offers_waitlist_entry_id'), 'waitlist_offers', ['waitlist_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlist_offers_waitlist_entry_id'), table_name='waitlist_offers')
    op.drop_index(op.f('ix_waitlist_offers_status'), table_name='waitlist_offers')
    op.drop_index(op.f('ix_waitlist_offers_show_seat_id'), table_name='waitlist_offers')
    op.drop_index(op.f('ix_waitlist_offers_id'), table_name='waitlist_offers')
    op.drop_index(op.f('ix_waitlist_offers_expires_at'), table_name='waitlist_offers')
    op.drop_index(op.f('ix_waitlist_offers_created_at'), table_name='waitlist_offers')
    op.drop_table('waitlist_offers')
    op.drop_index(op.f('ix_booking_seats_id'), table_name='booking_seats')
    op.drop_index(op.f('ix_booking_seats_created_at'), table_name='booking_seats')
    op.drop_table('booking_seats')
    op.drop_index(op.f('ix_waitlist_entries_user_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_status'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_event_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_created_at'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_category_id'), table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    op.drop_index(op.f('ix_show_seats_status'), table_name='show_seats')
    op.drop_index(op.f('ix_show_seats_physical_seat_id'), table_name='show_seats')
    op.drop_index(op.f('ix_show_seats_id'), table_name='show_seats')
    op.drop_index(op.f('ix_show_seats_hold_expires_at'), table_name='show_seats')
    op.drop_index(op.f('ix_show_seats_held_by_id'), table_name='show_seats')
    op.drop_index(op.f('ix_show_seats_event_id'), table_name='show_seats')
    op.drop_index(op.f('ix_show_seats_created_at'), table_name='show_seats')
    op.drop_table('show_seats')
    op.drop_index(op.f('ix_event_category_pricings_id'), table_name='event_category_pricings')
    op.drop_index(op.f('ix_event_category_pricings_created_at'), table_name='event_category_pricings')
    op.drop_table('event_category_pricings')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_event_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_reference'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_index(op.f('ix_seats_created_at'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_events_venue_id'), table_name='events')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index(op.f('ix_events_organiser_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_venues_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_created_at'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_seat_categories_id'), table_name='seat_categories')
    op.drop_index(op.f('ix_seat_categories_created_at'), table_name='seat_categories')
    op.drop_table('seat_categories')
    # ### end Alembic commands ###
